### ISSUE TITLE
Naming questions

### ISSUE THREAD

**Issue by katyo** [DelSkayn/rquickjs#10]
What about shortening `Error::FromJsConversion` to `Error::FromJs` and `Error::ToJsConversion` to `Error::ToJs`.
Short variant names is same as correspondent trait names.
Also I think the "conversion" already implied by prefix `From` and `To`.
To be fully Rust-ish we may also replace `To` in favor of `Into`.

**Comment by DelSkayn** [comment]
Agreed, I took the naming directly from the rlua crate but this seems more clear

**Comment by katyo** [comment]
> Agreed, I took the naming directly from the rlua crate but this seems more clear

Course, IIRC, lua allows pass multiple values via return too so that naming more reasonable in that case.

**Comment by katyo** [comment]
Seems it can be closed too.
