### ISSUE TITLE
How to use ctx: Ctx inside async function?

### ISSUE THREAD

**Issue by chertov** [DelSkayn/rquickjs#100]
Hi! I want to create JS Value inside async function, but when i try to get ctx the code doesn't compiles..
for example try to create ArrayBuffer
```Rust
async fn read_from_file<'js>(ctx: Ctx<'js>, path: String) -> rquickjs::Result<Value<'js>> {
    let byte_block = tokio::fs::read(path).await?;
    let array_buffer = ArrayBuffer::new(ctx, byte_block)?;
    let typed_arr = TypedArray::<u8>::from_arraybuffer(array_buffer)?;
    Ok(typed_arr.into_value())
}

ctx.globals().set("readFromFile", rquickjs::Func::from(Async(read_from_file)))?;
```
output:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/436625/205484913-89a1af09-06a6-40f7-81a9-ca093cd9a917.png">

What is the right way to create JS Value inside async context?

**Comment by richarddd** [comment]
Im running into this issue as well, any ideas @katyo?

**Comment by katyo** [comment]
@richarddd You cannot use `Ctx` in such way in async functions.
The `Ctx` is available in JS runtime contexts only (i.e. in `with`).
Maybe easiest way is create `newtype` wrapper for your data and implement `IntoJs` trait for it.

**Comment by richarddd** [comment]
> ```rust
> async fn read_from_file<'js>(ctx: Ctx<'js>, path: String) -> rquickjs::Result<Value<'js>> {
>     let byte_block = tokio::fs::read(path).await?;
>     let array_buffer = ArrayBuffer::new(ctx, byte_block)?;
>     let typed_arr = TypedArray::<u8>::from_arraybuffer(array_buffer)?;
>     Ok(typed_arr.into_value())
> }
> 
> ctx.globals().set("readFromFile", rquickjs::Func::from(Async(read_from_file)))?;
> ```

I just realized that conversion happens automatically:

```rust
async fn read_from_file<'js>(path: String) -> rquickjs::Result<Vec<u8>> {
    let bytes = tokio::fs::read(path).await?;
    Ok(bytes)
}

        ctx.globals()
                .set("readFromFile", rquickjs::Func::from(Async(read_from_file)))?;
```

**Comment by katyo** [comment]
@richarddd Is this issue resolved for you?

**Comment by katyo** [comment]
Looks like solved. Feel free reopen.

**Comment by richarddd** [comment]
Yes! Im taking the newtype wrapper approach 🙂
