### ISSUE TITLE
Holding on to unevaluated modules is unsound.

### ISSUE THREAD

**Issue by DelSkayn** [DelSkayn/rquickjs#117]
Currently in rquickjs it is possible to hold onto an unevaluated module by calling `Module::new`. This function returns a module which has been compiled but not yet evaluated and this module object can be held onto like any other js value in rquickjs.

However, this can result in undefined behaviour. The code for evaluating a module in rquickjs contains the following snippet:
```c
JSModuleDef *m;
m = JS_VALUE_GET_PTR(fun_obj);
/* the module refcount should be >= 2 */
JS_FreeValue(ctx, fun_obj);
if (js_create_module_function(ctx, m) < 0)
    goto fail;
if (js_link_module(ctx, m) < 0)
    goto fail;
ret_val = js_evaluate_module(ctx, m);
if (JS_IsException(ret_val)) {
fail:
    js_free_modules(ctx, JS_FREE_MODULE_NOT_EVALUATED);
    return JS_EXCEPTION;
}
```
In this snippet the function `js_free_modules` frees all modules which are not evaluated if an error happens during module evaluation, regardless of the reference count of the `JsValue` that held the object. This makes the following code unsound:

```rust
let runtime = Runtime::new().unwrap();

let ctx = Context::full(&runtime).unwrap();

ctx.with(|ctx| {
    let module_1 = Module::new(ctx, "mod1", "export function foo() {}")?;
    ctx.compile("mod2", "oh_no_an_error()").ok();
    module_1.eval()?;
    Ok(())
})
```
The `JsValue` in `module_1` is freed after the call to `Ctx::compile`. 

This also caused the corruption from issue #91 as our library assumed that a module still needed to be freed after an exception was raised during module evaluation.

Fixing this issue seems relatively difficult and might require a redesign of how the library handles modules.

**Comment by katyo** [comment]
If I remember correctly I separated evaluation and compilation to get bytecode compilation for build builtin JS modules because usually we no need evaluate modules in such case.

Maybe the better solution is change such strange behavior via patching quickjs to free the orphan modules only.

**Comment by DelSkayn** [comment]
After reading through quickjs code it seems that modules have a very different lifetime than normal `JsValue`. They don't seem to respect reference count at all as it isn't even possible to free them by reducing their reference count to zero.
Doing so causes quickjs to panic. 

I am not sure patching this behavior is a good idea. Quickjs seems to relay on how it is freeing modules internally. If we just patched the function to not drop modules which have a larger then zero reference count it would probably cause quickjs to leak memory. Any patch which changes this behavior would need to be pretty invasive, changing a large part of how quickjs functions.

**Comment by katyo** [comment]
Course, currently quickjs handles modules little bit dirty. Seems design comes from the fact that modules lives as long as a context and any not evaluated modules apriory treats as a outlived.

I propose get a rid of `Module<Loaded<Script>>` entity.
In my opinion it is possible reimplement API in a way that we never deal with it.
Currently there is two use cases for ES modules:
1. Load and compile module to generate bytecode.
2. Load and compile module (or load it from bytecode) and evaluate it.
