### ISSUE TITLE
Panicked on running cargo build

### ISSUE THREAD

**Issue by Silomalo** [DelSkayn/rquickjs#123]
error: failed to run custom build command for `rquickjs-sys v0.1.7` 

when running cargo build:

 --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\...\.cargo\registry\src\github.com-1ecc6299db9ec823\rquickjs-sys-0.1.7\build.rs:136:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by katyo** [comment]
@Silomalo Which OS you use to build?
Have you `patch` tool installed?

**Comment by Silomalo** [comment]
I am using windows, I have tried installing the patch but i can t find a clear way to do that. I have install vs build tools and SDk. How can I go about this?

**Comment by Silomalo** [comment]
Done: found it here- follow step by step and don't forget to give a like: https://www.youtube.com/watch?v=FbxNj53HxMw

**Comment by katyo** [comment]
I am considering applying patches without patch tool.
