### ISSUE TITLE
Detect when the task queue is empty?

### ISSUE THREAD

**Issue by stevefan1999-personal** [DelSkayn/rquickjs#137]
So NodeJS will shut itself down when there is nothing in the task queue, and I wonder how do I replicate this in Rust with `futures` feature on. Right now it seems like the executor task would like to run forever if I selected it, but if I don't select it in my run loop and let the Tokio runtime die before then it will panic due to SendError. I want to detect when the queue is empty so I can shut down the runtime.

**Comment by katyo** [comment]
@stevefan1999-personal See [Runtime::idle](https://docs.rs/rquickjs/latest/rquickjs/struct.Runtime.html#method.idle)

**Comment by stevefan1999-personal** [comment]
[https://github.com/DelSkayn/rquickjs/blob/234cc91ff7a3d06fb5d58fcd8f0e6bed56af51d5/core/src/runtime/async_executor.rs#L69](https://github.com/DelSkayn/rquickjs/blob/234cc91ff7a3d06fb5d58fcd8f0e6bed56af51d5/core/src/runtime/async_executor.rs#L69)

I once turned on debugger and see that after the timer tasks are done, this is hit and the select loop is never triggered again for some reason.

**Comment by DelSkayn** [comment]
This issue should be resolved now that futures where redesigned. `AsyncRuntime::idle` should only return after all futures and promises are finished.

**Comment by stevefan1999-personal** [comment]
@DelSkayn I wonder if there is an tutorial for the new future design?
