### ISSUE TITLE
rquickjs::Error::Exception should preserve the original value

### ISSUE THREAD

**Issue by RReverser** [DelSkayn/rquickjs#138]
In JavaScript, while uncommon, it's possible to throw arbitrary values, not just `Error` objects and some libraries actually make use of it.

Right now `rquickjs` doesn't allow to retrieve this non-`Error` value and fails with conversion errors instead, as the `Exception` variant can't represent anything but error objects:

```rust
Exception {
    message: StdString,
    file: StdString,
    line: i32,
    stack: StdString,
},
```

Example:

```rust
fn main() {
    let runtime = rquickjs::Runtime::new().unwrap();
    let context = rquickjs::Context::full(&runtime).unwrap();
    context.with(|ctx| ctx.eval::<(), _>("throw 42;")).unwrap();
}
```

results in the following conversion error, with no way to retrieve the original error value:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromJs { from: "int", to: "object", message: None }', /home/rreverser/.cargo/git/checkouts/rquickjs-da202ee7abfef64e/29c5454/core/src/result.rs:478:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

For compatibility with arbitrary JS code, it should be possible to retrieve the original `rquickjs::Value` from the exception. As far as I can tell, QuickJS provides this functionality, and the conversion is imposed only at the rquickjs level.

**Comment by holly-hacker** [comment]
To be clear: this is a panic inside rquickjs and not in the user code.

**Comment by RReverser** [comment]
No, this is a panic in my own example code, where I'm unwrapping the result.

**Comment by RReverser** [comment]
Oh I see what you mean; yeah good point.
