### ISSUE TITLE
Compilation tests issues

### ISSUE THREAD

**Issue by katyo** [DelSkayn/rquickjs#14]
Using _trybuild_ for compilation tests has an issues related to repeatability on different Rust compiler versions.
Currently this test pass successfully only on Rust beta.

**Comment by katyo** [comment]
I temporary disabled tests in #13

**Comment by DelSkayn** [comment]
Trybuild's error checking seems pretty closely tied to the compiler version and even the version of dependencies. 
While I like the idea of a test that prevents accidentally breaking the safety constraints of `Ctx`, trybuild is currently only used in a single test and the change that we break `Ctx`'s api is pretty unlikely. So it think we can just remove the test.

**Comment by katyo** [comment]
Agree with you, currently compilation test is not so matter.

I tried migrate to __compiletest_rs__ but it works not so well too.
Particularly, I have compilation problems related to `use rquickjs::*`.
Seems it requires create another crate for tests.

**Comment by katyo** [comment]
Disabled by default in #13 
Can be run by using `--feature compile-test`.
