### ISSUE TITLE
Change `embed` macro.

### ISSUE THREAD

**Issue by DelSkayn** [DelSkayn/rquickjs#144]
The current `embed` macro semantics are a bit strange.

The macro is used as following:
```rust
#[embed(path = "./path/to/files")]
mod module_name{}
```
This creates a bundle loaded into as static with name `BUNDLE_NAME` and try to load `module_name.js` from the `./path/to/files` relative to the root of the crate. Multiple files can be loaded by using the `name` attribute. The resulting bundles is both a loader and a resolver. 

This behavior is somewhat strange as we use the `mod` keyword to declare the bundle but a bundle isn't a module. The current implementation is also a bit of a hack as we actually use quickjs to resolve the files and hijack the resolver and loader to retrieve the loaded modules.

I think a better method of implementing this macro something like the following:
```rust
const BUNDLE: Bundle = embed!{
    "./path/to/files/module_name.js": "module_name",
}
```
This makes it more clear that it creates a bundle and where it is loaded from.

**Comment by DelSkayn** [comment]
Closing as it was implemented in #146

**Comment by katyo** [comment]
@DelSkayn

I think the colon between path and module name may confuse. I propose use `=>` instead or swap module name and path.

```rust
const BUNDLE: Bundle = embed!{
    "./path/to/files/module_name.js" => "module_name",
    "./path/to/files/module_name.js",
}
// or
const BUNDLE: Bundle = embed!{
    "module_name": "./path/to/files/module_name.js",
    "./path/to/files/module_name.js",
}
```

**Comment by katyo** [comment]
@DelSkayn It confused for me because this is not looks like a case of binding.

**Comment by DelSkayn** [comment]
@katyo alright, fair enough, I will swap the name and path.
