### ISSUE TITLE
Best place to share utils?

### ISSUE THREAD

**Issue by Sytten** [DelSkayn/rquickjs#164]
Hi!
I am building a couple of utils that I think could be useful to the community.
The first one is a full `Console` implementation that handles all the types of values.
I think it would be worth sharing I am just wondering if you should create a `rquickjs-extra` repo/crate? Or maybe just examples.
Let me know!

**Comment by ahaoboy** [comment]
Is there a demo available for use? I've tried rewriting the console api in Rust before, but it became too complex, eventually give up. That is indeed a very massive project 👍

**Comment by Sytten** [comment]
I need to update our rquickjs but happy to share once thats done

**Comment by stephencroberts** [comment]
@Sytten Are you planning to make it part of the LLRT modules? Would love to see your `Console` implementation if it's finished. LLRT's has a lot of lambda code in it and doesn't have all of the features.

**Comment by Sytten** [comment]
Yeah I will move it to llrt modules if possible. I still need to put an interface so llrt can still use their stuff.

**Comment by Sytten** [comment]
I am closing this issue since the place is now: https://github.com/awslabs/llrt/tree/main/llrt_modules
