### ISSUE TITLE
Which platforms are supported?

### ISSUE THREAD

**Issue by yuanyan3060** [DelSkayn/rquickjs#185]

**Comment by DelSkayn** [comment]
Hi!

Rquickjs should be able to build anywhere you can run the clang compiler, patch, and  `bindgen` and is supported by rust.
We have official bindings for a bunch of platforms, they can be found in `sys/src/bindings/`. 
If your platform is not among the list of official bindings please try and enable the `bindgen` feature for rquickjs and the library should then generate bindings for the correct platform when building.

If you are building for a less commonly used platform, it should work but it isn't tested.
If you encounter problems feel free to raise an issue.
