### ISSUE TITLE
Persistent no longer implements Hash, Eq etc

### ISSUE THREAD

**Issue by richarddd** [DelSkayn/rquickjs#187]
Seems like this got removed from the class refactoring PR. It's now no longer possible to store Values in a Hash map.

**Comment by DelSkayn** [comment]
I added a derive for Eq and Hash to persistant. Since all javascript values implement Eq and Hash this should allow the persistant object to be stored in hashmaps again.

**Comment by richarddd** [comment]
I see it's implemented for each JS value (Object,Function etc) but not for `Value` itself.

**Comment by DelSkayn** [comment]
I reimplemented the Hash and Eq  in 8b2079c are you on that commit or more recent?
If you are still using the latest 0.4.0-beta version, I haven't pushed out a version with those changes yet.

**Comment by richarddd** [comment]
> I reimplemented the Hash and Eq in [8b2079c](https://github.com/DelSkayn/rquickjs/commit/8b2079ca77aaa278388b354af6f3e8673a74b110) are you on that commit or more recent?
> If you are still using the latest 0.4.0-beta version, I haven't pushed out a version with those changes yet.

Saw that now thanks. That solves it
