### ISSUE TITLE
Invert  #[qjs(skip_trace)] -> #[qjs(trace)]

### ISSUE THREAD

**Issue by richarddd** [DelSkayn/rquickjs#195]
Isn't it better to tell what to trace than what not to trace in the derive?
`#[qjs(skip_trace)]` should in my opinion be inverted and be used as  `#[qjs(trace)]` on fields we want to trace.

**Comment by DelSkayn** [comment]
I personally prefer to always lean towards doing the safe and correct thing by default and error when it is not supported. Which I find is how rust generally does things. Failing to trace can result in aborts or memory leaks so this is why I made the macro such that you need to manually mark fields to not be traced making the implementer think about whether a field could contain traceable pointers

**Comment by richarddd** [comment]
Makes sense!
