### ISSUE TITLE
Support Windows Arm64

### ISSUE THREAD

**Issue by qiyuey** [DelSkayn/rquickjs#207]
When Clash Verge wanted to support Windows arm64, we found that rquickjs did not support it, so we hope that rquickjs can support this platform.
https://github.com/zzzgydi/clash-verge/issues/230

**Comment by DelSkayn** [comment]
We don't provide bindings for windows-aarch64 because we don't have CI support for building and testing on that platform. However rquickjs should build on that platform with the `bindgen` feature enabled. 

Did you try to enable the `bindgen` feature?
