### ISSUE TITLE
as_bytes_mut is missing for ArrayBuffer

### ISSUE THREAD

**Issue by stevefan1999-personal** [DelSkayn/rquickjs#214]
```
    pub fn as_bytes_mut(&mut self) -> Option<&mut [u8]> {
        let (len, ptr) = Self::get_raw(self.as_value())?;
        Some(unsafe { slice::from_raw_parts_mut(ptr, len) })
    }
```
This is needed to implement TextEncoder

**Comment by DelSkayn** [comment]
The provided code would allow you to have aliasing mutable references to the same slice, by cloning the ArrayBuffer object and then calling that method on both objects. This would be unsound. I will see if I can provide a mutable way to access the bytes but it would require implementing some `RefCell` like functionality which is currently not present.

**Comment by DelSkayn** [comment]
Closing this issue as supporting the feature would be unsound.
