### ISSUE TITLE
about some use cases and tutorial documents

### ISSUE THREAD

**Issue by yancheng199287** [DelSkayn/rquickjs#23]
Does this crate support extending the native capabilities of quick JS by using rust?
After reading your project code, it seems that I am not very clear about the use of some APIs. Can you add some wikis or more cases to illustrate the demo function? When I run the main method of example directly from windows, it doesn't seem to work properly? thank you

**Comment by katyo** [comment]
@yancheng199287 Can you describe that you try to do and that goes wrong?

Currently this crate supports different OSes including: linux, macos and windows.
Multiple tests runs in CI to check compatibility.
However docs and examples still incomplete and needs more work.

**Comment by yancheng199287** [comment]
I want to add struct,like this:

struct User {
    username: String,
    email: String,
    sign_in_count: u64,
    active: bool,
}

fn build_user(email: String, username: String) -> User {
    User {
        email,
        username,
        active: true,
        sign_in_count: 1,
    }
}

impl User{
    
    fn introduce(self){
        println!("{} {}",self.username,self.email)
    }
}
and I want to use User in JS , like this

let user=new User("Jason","xxxxx@gmail.com",false,10);
user.introduce();
how to do it? thanks!

**Comment by katyo** [comment]
The easy way to do something like this provides `bind` macro.
See class example here:
https://docs.rs/rquickjs/0.1.1/rquickjs/attr.bind.html#class-binding

**Comment by yancheng199287** [comment]
ok，thanks. This is a really good example. I’ve learned how to call RUST in JS, But I don’t know how to call JS code in RUST, how do they pass data to each other?

**Comment by yancheng199287** [comment]
I found an example in the source code, is that right? But I’m curious, how does this JS class work?
```
ctx.with(|ctx| {
        let mut module: Module = ctx
            .compile(
                "Test",
                r#"
            export var a = 2;
            export function foo(){ return "bar,hello I am ok!"}
            export class Baz{
                quel = 3;
                constructor(){

                }
            }
                "#,
            )
            .unwrap();
        let entries = module
            .entries()
            .collect::<Result<Vec<(String, Value)>>>()
            .unwrap();
        for entry in entries {
            println!("===> {:?}", entry);
        }
        let func: Function = module.get("Baz").unwrap();
         print!("is construct:{}",func.is_constructor());
        func.set_constructor(true);
        let re = func.call::<(), String>(()).unwrap();
        print!("re:{}", re);
    });

```

```
===> ("a", Int'('2')')
===> ("foo", Function'('0x187bd5dc080')')
===> ("Baz", Function'('0x187bd5dba80')')
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exception { message: "class constructors must be invoked with \'new\'", file: "", line: -1, stack: "    at Baz (Test:6)\n" }', examples\rust_call_js_export.rs:34:46
stack backtrace:
```

**Comment by katyo** [comment]
@yancheng199287 You should use `public` attribute like the following:
```rust
use rquickjs::{bind};

#[bind(object, public)]
#[quickjs(bare)]
mod user {
...
```

The `pub mod` is related to module not the bindings.

**Comment by yancheng199287** [comment]
That’s a good design. Thank you
