### ISSUE TITLE
native binding hide behind bundled module

### ISSUE THREAD

**Issue by hh9527** [DelSkayn/rquickjs#24]
I want to provide builtin functions and these functions require native binding, but I don't want these native bindings exposed to user code. For example:

```js
// my bundled module 'http'
export async function fetchJson(uri) {
  const text = await __native_api__.fetch_text(uri);
  return JSON.parse(text);
}
```

```rust
// my native bindings
#[rquickjs::bind(object, public)]
#[quickjs(rename = "__native_api__")]
mod native_api {
    pub async fn fetch_text(url: String) -> Result<String> {
        // native implementation here
    }
}
```

this approach will cause `__native_api__` exposed as global variable. how could I avoid global `__native_api__`?

**Comment by katyo** [comment]
@hh9527,
You may either remove `public` attribute or assign concrete scope to it.
See `bind` docs https://docs.rs/rquickjs/0.1.1/rquickjs/attr.bind.html#macro-attributes.

**Comment by katyo** [comment]
@hh9527 This issue looks resolved. Can we close it?

**Comment by katyo** [comment]
Closed due to inactivity for a while.
Feel free to reopen if this issue still alive.
