### ISSUE TITLE
Update QuickJS to latest version and submit patches to repo

### ISSUE THREAD

**Issue by richarddd** [DelSkayn/rquickjs#246]
Development for QuickJS has now resumed 🥇 . It would be a good idea to submit the patches to the original repo.

https://github.com/bellard/quickjs/commits/master/

**Comment by richarddd** [comment]
@DelSkayn I took a closer look at this. There are a few patches that we can remove and some that can be moved to rquickjs and overall it should be relatively smooth to update engine, 

## Patches

### atomic_new_class_id.patch
Not needed - merged
 
### basic_msvc_compat.patch
Needed - needs rebase
 
### check_stack_overflow.patch
Needed - no rebase required
 
### dynamic_import_sync.patch
Needed - Would need rework
 
### error_column_number.patch
Needed - Would require significant update

### get_function_proto.patch
Needed - no rebase required
 
### infinity_handling.patch
Needed - no rebase required
 
### read_module_exports.patch
Needed - needs rebase

## Other noticeable differnces
- Top level await is now added  🎉
- ES2023 🎉
- `JS_RunModule` is now `JS_LoadModule`
- `JS_GetModuleNamespace` is now available so might not require `read_module_exports.patch`

**Comment by Sytten** [comment]
I saw the resumed progress, it is so cool! Lot of the work from quickjs-ng is getting merged too. Hopefully we can keep it up to date to benefit from the updates.

**Comment by richarddd** [comment]
> I saw the resumed progress, it is so cool! Lot of the work from quickjs-ng is getting merged too. Hopefully we can keep it up to date to benefit from the updates.

Yes its fantastic! The two projects will eventually merge.

I have updated all the patches except for one. The only blocker I have right now is the ability to do a blocking promise await from rust AND drive event loop forward. In QuickJS this is done through [js_std_await](https://github.com/bellard/quickjs/blob/6a89d7c27099be84e5312a7ec73205d6a7abe1b4/quickjs-libc.c#L3971)

**Comment by DelSkayn** [comment]
Closing as rquickjs has updated to the latest quickjs release in #293.
