### ISSUE TITLE
musl support

### ISSUE THREAD

**Issue by hh9527** [DelSkayn/rquickjs#25]
`cargo build --target x86_64-unknown-linux-musl`

got the following message:

```text
error: couldn't read /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.1.0/src/bindings/x86_64-unknown-linux-musl.rs: No such file or directory (os error 2)
  --> /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/rquickjs-sys-0.1.0/src/lib.rs:13:1
   |
13 | include!(concat!("bindings/", bindings_env!("TARGET"), ".rs"));
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by hh9527** [comment]
Oh, i need `bindgen`, and it works. The bindgen requires libclang/clang/llvm, the environment requirement is a bit complex for our team. Can you ship musl version in release?

**Comment by katyo** [comment]
@hh9527 We need some changes in CI workflow to add musl targets.
I hope it is easy to do but currently I'm little bit busy. Could you try to do it and make pull request?
