### ISSUE TITLE
Exposing bridged APIs

### ISSUE THREAD

**Issue by BodaciousPie** [DelSkayn/rquickjs#252]
Hello, 

I'm building a command line executable which exposes many rust APIs using the binding macros. I'd like the CLI app users to invoke custom scripts to utilise these APIs. 

Is there an easy way for me to generate a companion file or module which details the bridged APIs? This would enable IDEs to aid script authors with code hints, autocomplete, etc. 

Thanks!

PS: awesome crate!

**Comment by DelSkayn** [comment]
Hi! Glad you like the crate.

Unfortunately there is no such method in rquicks or the library it builds upon Quickjs. You will have to create such files manually.

**Comment by DelSkayn** [comment]
Closing as this question should be answered.
