### ISSUE TITLE
how to defined a function with variable argument size by macro 'rquickjs::function'

### ISSUE THREAD

**Issue by LXS2000** [DelSkayn/rquickjs#256]
there is a function i created,jsreq is necessary， the remaining arguments is optional
```rust

#[rquickjs::function]
pub async fn fetch<'js>(
jsreg: JsRequest.
proxy: Option<String>
ja3: Option<i64>,
h2: Option<i64>
ctx: Ctx<'js>,
)-> Result<JsResponse>
```

when i use it in js runtime ，i got a error
> Error calling function with 2 argument(s) while 4 where expected

**Comment by LXS2000** [comment]
```js
await fetch(request, proxy)
```

**Comment by DelSkayn** [comment]
Using `Option<T>` as an argument signifies to rquickjs that the value can be null-like i.e. either the value `T` `undefined` or `null` but that the argument is still required. If you want the argument to be optional use [`Opt`](https://docs.rs/rquickjs/latest/rquickjs/function/struct.Opt.html)

**Comment by LXS2000** [comment]
Thank you for your answer ,it's work
