### ISSUE TITLE
How to import an external module script into an executing script file for eval_file function?

### ISSUE THREAD

**Issue by yancheng199287** [DelSkayn/rquickjs#26]
```

 let f="D:\\test.js";
 ctx.eval_file::<String,String>(f.parse().unwrap()).unwrap();

```

test.js

```
import { n} from "script_module";
print(s);

```

error message

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exception { message: "expecting \'(\'", file: "test.js", line: 1, stack: "    at test.js:1\n" }', examples\with_module.rs:45:60
stack backtrace:

```

I may need to execute a javascript script file, but the script file needs to import another script file. So, what do we do?

**Comment by katyo** [comment]
Fns like an `eval_file` is from old API, which may be deprecated and removed later. I recommend you use `Module::new` and `Module::eval` instead. It should works with ES6 modules.

**Comment by yancheng199287** [comment]
ok,thanks.   It is too esay to use a wrapper method ，like ctx.compile().     

I'm learning all kinds of things about this library, I've researched a lot of JS engine crate, and I think this one is the best. I hope you can help me with this knowledge. I will share more practical cases or help you improve the document. Thank you! That said, you're such a sweet developer.

**Comment by katyo** [comment]
Thank you. It shall be very helpful to add more code samples and extend docs.

**Comment by katyo** [comment]
@yancheng199287 Can we close this issue?

**Comment by katyo** [comment]
Closed due to inactivity for a while.
Feel free to reopen if this issue still alive.
