### ISSUE TITLE
rust function with variable number of params

### ISSUE THREAD

**Issue by FlondorDev** [DelSkayn/rquickjs#260]
hi, how do i create a function that can accept multiple params?

**Comment by DelSkayn** [comment]
That depends on how you want accept the params. If you want a single optional argument use [`Opt`](https://docs.rs/rquickjs/latest/rquickjs/function/struct.Opt.html). If you want to accept all remaining arguments use [`Rest`](https://docs.rs/rquickjs/latest/rquickjs/function/struct.Rest.html). If your requirement is more complex you will have to manually implement [`IntoJsFunc`](https://docs.rs/rquickjs/latest/rquickjs/function/trait.IntoJsFunc.html) and then parse out the params manually.

**Comment by FlondorDev** [comment]
ok, thanks i was searching for Rest.
