### ISSUE TITLE
How to import `console` object in rquickjs?

### ISSUE THREAD

**Issue by getong** [DelSkayn/rquickjs#309]
The code:
```
use rquickjs::{async_with, AsyncContext, AsyncRuntime};

#[tokio::main]
async fn main() {
  let rt = AsyncRuntime::new().unwrap();
  let ctx = AsyncContext::full(&rt).await.unwrap();

  async_with!(&ctx => |ctx| {
    if let Ok(res) = ctx.eval::<(), &str>("console.log(\"hello world\");") {
      println!("Result: {:?}", res);
    } else {
      println!("Failed to evaluate JavaScript code");
    }

    if let Ok(res) = ctx.eval::<i32, &str>("2 + 5") {
      println!("Result: {:?}", res);
    } else {
      println!("Failed to evaluate JavaScript code");
    }
  })
  .await;
}
```
The run result is 
```
Failed to evaluate JavaScript code
Result: 7
```
I think `console.log("hello world")` is  `()`, the unit type in rust.
But it does not work here.

**Comment by getong** [comment]
It seems that, the `console` object does not import here.
How can I import javascript `console` object here?

**Comment by richarddd** [comment]
There is no console. You have to build it yourself

**Comment by DelSkayn** [comment]
There is indeed no console object in rquickjs you will have to build it yourself. 

Also note that if you call `catch` on the result from the trait [`CatchResultExt`](https://docs.rs/rquickjs/latest/rquickjs/trait.CatchResultExt.html) you will get the actual error returned by quickjs which would have told you that console didn't exist. By default exceptions are only stub, you will have to actually retrieve the error from the context to get the full error.
