### ISSUE TITLE
"Registry" is misspelled as "registery" in the public API (feature/type/function names)

### ISSUE THREAD

**Issue by chitoyuu** [DelSkayn/rquickjs#32]
The word "registry" is misspelled as "regist**e**ry" in the public API (feature/type/function names). 

Wiktionary: https://en.wiktionary.org/wiki/registry
Wiktionary page for "register": https://en.wiktionary.org/wiki/register#Derived_terms

This could be fixed in the next minor version.

**Comment by katyo** [comment]
I planned to remove this deprecated API
