### ISSUE TITLE
Assertion failed: list_empty(&rt->gc_obj_list)

### ISSUE THREAD

**Issue by stolen-programmer** [DelSkayn/rquickjs#332]
Assertion failed: list_empty(&rt->gc_obj_list), file D:\work\RustroverProjects\jmake\target\debug\build\rquickjs-sys-f05193e5ce683c59\out\quickjs.c, line 2001

[复现](https://github.com/stolen-programmer/jmake/tree/recurrent)

**Comment by Sytten** [comment]
@stolen-programmer please make an error to report correctly the error and in english, otherwise we should close the issue
