### ISSUE TITLE
Snapshots

### ISSUE THREAD

**Issue by gc-victor** [DelSkayn/rquickjs#335]
It would be great to have snapshots like these. @DelSkayn, is there any way to implement it?

https://github.com/rscarson/rustyscript/blob/master/src/snapshot_builder.rs

**Comment by DelSkayn** [comment]
We might be able to support something like it, I know QuickJS has the ability to dump to bytecode, which can also include state, so you might be able to work out some sort of snapshot system with that.

This would require some investigation.

**Comment by gc-victor** [comment]
Awesome!
I want to push this initiative, which would be a huge step forward. Could you please give me a hint so I can check it? I don't know C, so I won't get any closer to a solution, but I will try it.

**Comment by gc-victor** [comment]
@DelSkayn, after a quick look at the QuickJS docs and the code, I noticed that what you mentioned in your comment could be the compile_file from qjsc.c.

The main parts:
- `js_load_file`
- `JS_Eval`
- `output_object_code`

The `output_object_code` uses internally `JS_WriteObject`, the same as the `write` function in the module.rs.

LLRT uses the `write` to create a kind of compile code, but I tried a similar approach, and the result wasn't satisfactory.

References:

- https://github.com/bellard/quickjs/blob/5417ab0159fc48c217ff91344a833d3286b8895d/qjsc.c#L281
- [https://github.com/DelSkayn/rquickjs/blob/1a398d972e0cf2d9a8ae096f33596d80311a79cc/core/src/value/module.rs](https://github.com/DelSkayn/rquickjs/blob/1a398d972e0cf2d9a8ae096f33596d80311a79cc/core/src/value/module.rs#L393)

**Comment by ahaoboy** [comment]
txiki has similar functionality, implemented in C
https://github.com/saghul/txiki.js/blob/e2f6d9358bffef971e86ac2655fc30b03bfad361/src/mod_engine.c#L73

**Comment by gc-victor** [comment]
My aim with this approach was to try to solve the response time, but as @richarddd   mentioned in Discord, it will probably only help with the startup time. The problem was that I was creating a new runtime for each request. Fixing it, I decreased the response time five times; we are talking about moving from around 15ms to 3ms. On the other hand, I didn't see any difference in the response time between caching the bytes and using `Module.load` and not doing it.
