### ISSUE TITLE
ClassId clash among instances of generic types

### ISSUE THREAD

**Issue by FrankHB** [DelSkayn/rquickjs#340]
Expansion of `#[class]` will have a `static` objects `fn class_id() `. Unfortunately, there is still one instance when the struct is generic, due to the fact Rust share the static object for all instances (which is different in some other languages like C++). This would make very nasty bugs when more than one instances are registered to one runtime instance, when the wrong finalizers are eventually called unexpectedly.

(Also note the generated instances of `NAME` should not clash.)

A workaround is to reimplement the result from the `class` macro with injected members from additional traits describing the `NAME` and non-shared `fn class_id` implementations. This still meets the difficulties when used across different crates for problems raised by orphan rules. Thus, I believe it is better to be fixed in the crate `rquickjs_macro`.

**Comment by DelSkayn** [comment]
Hmmm, this definitely a problem. I wasn't aware of this behavior.

I don't see a good way around this problem, the best solution I see is just disallowing generics on the class attribute, and force people to implement the class method on fully specified types, maybe allowing implementing it on type aliases.

Could you maybe expand on the workaround you mentioned? 

The instances of name should clash I think. The implementation of class for a generic struct is
```rust
struct Foo<T>{ t: T};
impl<'js,T> JsClass<'js> for Foo<T>{
    const NAME: &'static str = "Foo";
}
```
So name is the same for every T.
 I already expected them to class but didn't think it was that much of a problem as it the NAME wasn't critical for safety.

**Comment by FrankHB** [comment]
# Current workaround

In my case I need some types to get `Rc<RefCell<T>>` work (passed around JS and Rust code) with many `T`. I have a wrapper struct and a templated mixin like this:


```rust
#[derive(derivative::Derivative)]
#[derivative(Clone(bound = ""))]
pub struct W<T: ?Sized> {
    pub value: Rc<RefCell<T>>
}
// XXX: #[rquickjs::class] does not work here. It seems also clashing with tuple struct.
// ... impl as #[rquikjs::class] omitted.

pub trait ClassDesc
{
	const NAME: &'static str;

	fn class_id() -> &'static ClassId;
}

macro_rules! define_desc {
	($ty: ty) => {
		impl $crate::ClassDesc for $ty {
			const NAME: &'static str = stringify!($ty);

			fn class_id() -> &'static $crate::rquickjs::class::ClassId {
				static ID: $crate::rquickjs::class::ClassId
					= $crate::rquickjs::class::ClassId::new();

				&ID
			}
		}
	}
}

define_desc!(W<SomeT>);

```

And then I have to roll my own impl for `JsClass` instead to use the type.

This is verbose and annoying, but it works (plus a chance of opted-in custom `NAME` if needed), except that in other crates it is bitten by the orphan rules... So I have to come up with even one more type:

```rust
#[rquickjs::class(crate = "rquickjs")]
#[derive(Clone)]
pub struct MyNewType
{
	pub value: Rc<RefCell<SomeOtherT>>
}
```

This case `#[rquickjs::class]` works just because it is not generic. It still not resolve the original issue.

# Addition notes

Summarize up: I have multiple issues that I haven't figured out how to fix gracefully (but I believe they look like better to be resolved in `rquickjs_*` after I've struggled to find workarounds for months):

1. Passing `Rc<RefCell<T>>` values across JavaScript/Rust code boundary by reference instead of copying/moving the value of `T` (which defeats the purpose to use `Rc<RefCell<...>>`).
2. Using `#[rquickjs::class]` on tuple structs.
3. **This issue:** Using `#[rquickjs::class]` on generic structs mapping to different JavaScript classes (without unexpected sharing).
4. Providing methods on JavaScript methods on classes bound from `Rc<RefCell<T>>` with existing methods implementation actually from the Rust type `T` (like Rust's `deref`).
5. Type coercion (instead of explicit conversion) of upcast: making the values of JavaScript class bound from `Rc<RefCell<T>>` to those of JavaScript class bound from `Rc<RefCell<dyn Trait>>` implicitly, when `T` implements `Trait`.

They are likely deserving separated issues, but as a background I'd just list them here. Before filing more issues, I wonder if they are a series of X-Y problems due to missing of more idiomatic uses.

**Comment by FrankHB** [comment]
> Hmmm, this definitely a problem. I wasn't aware of this behavior.
> 
> I don't see a good way around this problem, the best solution I see is just disallowing generics on the class attribute, and force people to implement the class method on fully specified types, maybe allowing implementing it on type aliases.
> 
> Could you maybe expand on the workaround you mentioned?
> 
> The instances of name should clash I think. The implementation of class for a generic struct is
> 
> ```rust
> struct Foo<T>{ t: T};
> impl<'js,T> JsClass<'js> for Foo<T>{
>     const NAME: &'static str = "Foo";
> }
> ```
> 
> So name is the same for every T. I already expected them to class but didn't think it was that much of a problem as it the NAME wasn't critical for safety.

Yes, it will clash as per the current implementation. I have meant, the names are expected to avoid the clash by client code where the generic instances are mapped to separated JavaScript classes intentionally.
