### ISSUE TITLE
Allow registering arbitrary data to runtime

### ISSUE THREAD

**Issue by Sytten** [DelSkayn/rquickjs#342]
Hi!

This might seem weird, but I would like to be able to attach arbitrary Rust data to the runtime like we can do in web frameworks like [actix-web data](https://docs.rs/actix-web/latest/actix_web/web/struct.Data.html).
The reasoning is that currently in `llrt_module` we use global variables for that purpose, which is all fine when you have one runtime but not when you have multiple. So ideally I would attach that atomic to the runtime and I could get it back using the `Ctx` object. I guess we could wrap that in a class with a global JS value, but it's a bit ugly for no reason since only rust code should access those.

https://github.com/awslabs/llrt/blob/796dea3505658fea58569ad66c68c1dac8a459e4/llrt_modules/src/modules/perf_hooks.rs#L14

Thanks

**Comment by ahaoboy** [comment]
There are some global variables VERSION, TIME_ORIGIN, TIMER_ID. If they are mounted on runtime or vm, many functions will need to add a parameter, and it may be complicated due to lifetime restrictions.

```
fn print_version() {
    println!("LLRT ({} {}) {}", get_platform(), get_arch(), VERSION);
}
```

```
fn now() -> f64 {
    let now = Utc::now().timestamp_nanos_opt().unwrap_or_default() as f64;
    let started = TIME_ORIGIN.load(Ordering::Relaxed) as f64;

    (now - started) / 1e6
}
```

A simple way is to use Symbol as the key to put the variable on globalThis.
```
const k = Symbol("llrt_now")
Object.defineProperty(globalThis, k, {
  value: 0,
  configurable: false,
  enumerable: false
});
```

**Comment by Sytten** [comment]
We can use JS, but since this is rust <-> rust stuff it makes more sense to store it in rust. I discussed it on Discord yesterday but essentially it is an `HashMap<TypeId, Box<dyn Any>>`. I would use it via `ctx.data::<MyType>()` to retrieve a ref. Usually it is only possible to insert into it at creation time for the runtime.

**Comment by DelSkayn** [comment]
With #345 this is now supported.

**Comment by stevefan1999-personal** [comment]
Just as a workaround I set the value in the global context with a special key:
```rust
                ctx.globals().set(
                    "WORLD_END",
                    CancellationTokenWrapper {
                        token: stop_token.clone(),
                    },
                )?;
```
Then it retrieve it like this:
```rust
pub trait WorldsEndExt {
    fn worlds_end(&self) -> CancellationToken;
}

impl WorldsEndExt for rquickjs::Ctx<'_> {
    fn worlds_end(&self) -> CancellationToken {
        self.globals()
            .get::<_, CancellationTokenWrapper>("WORLD_END")
            .map(|x| x.token.child_token())
            .unwrap_or_else(|_| CancellationToken::new())
    }
}
```
