### ISSUE TITLE
Async function eval

### ISSUE THREAD

**Issue by tothalex** [DelSkayn/rquickjs#348]
Can anyone help me with a simple example of how to evaluate a JS file, get an async function, and execute it?

Example JavaScript Code:
```js
const main = () => {
  return 1 + 1
}

export default main
```

What I'm trying to do:
```rust
    pub async fn execute(path: &Path) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let code = fs::read_to_string(path).unwrap();

        let runtime = AsyncRuntime::new().unwrap();
        let context = AsyncContext::full(&runtime).await.unwrap();

        async_with!(context => |ctx| {
            let mut options = EvalOptions::default();

            options.promise = true;
            options.global = false;


            let result = ctx.eval_with_options::<Promise, _>(code, options).unwrap();
            let _ = result.into_future::<Value>().await.unwrap();
            let handler: Value = ctx.globals().get("default").unwrap();

            dbg!(handler);
        })
        .await;

        Ok(())
    }
```

But no luck I'm keep getting this `handler = Undefined"undefined"` can't get even to the execute phase.

Additional JavaScript Examples:
```js
const main = () => {
  return 1 + 1
}

export { main }
```

Example
```js
const main = () => {
  return 1 + 1
}

export {
  handler: main
}
```

**Comment by DelSkayn** [comment]
So, you seem to want to run a module, which you can't with eval. Eval can only run normal scripts. You need to use the [`Module`](https://docs.rs/rquickjs/latest/rquickjs/struct.Module.html) struct. First `declare()` it and the cal `evaluate()` on the module. You will then be able to retrieve the exports with `get()`
