### ISSUE TITLE
Trouble registering class and static method

### ISSUE THREAD

**Issue by ryangjchandler** [DelSkayn/rquickjs#38]
Given the following binding:

```rust
#[bind(object, public)]
#[quickjs(bare)]
mod flags {
    pub struct Flag;

    impl Flag {
        pub fn get() -> String {
            String::from("static stuff")
        }
    }
}

// other irrelevant code here...

context.with(|ctx: rquickjs::Ctx| {
    let glob = ctx.globals();

    glob.init_def::<Flags>().unwrap();

    ctx.eval::<(), _>("Flag.get()").unwrap();
})
```

Results in a "Flag is not defined" error. Adding a `pub fn new() -> Self` method to the `Flag` struct results in the following:

```
FromJs { from: "null", to: "prototype", message: Some("Unregistered class") }
```

Not immediately clear what's going wrong.

**Comment by ryangjchandler** [comment]
Okay, so after some experimenting it looks like that the `#[bind]` macros will only correctly register a class if it has a constructor (`pub fn new() -> Self`) and at least one instance method.

Is this the correct behaviour or perhaps a bug?

**Comment by katyo** [comment]
IIRC currently only constructor is absolutely needed.

**Comment by ryangjchandler** [comment]
Yeah, I couldn't get it to work without at least one instance method. I was getting that prototype error in the original issue.

**Comment by katyo** [comment]
This is related to ECMA Script design and partially to QuickJS implementation.
We need some function (so called constructor) to assign prototype and instantiate class.

But prototype may still empty object.
So if it does not works this is unexpected behavior and possibly a bug.

**Comment by ryangjchandler** [comment]
Yeah, I'm happy to dig into it a little more to see what's going wrong with the prototype. Not entirely sure on the internals though.

**Comment by katyo** [comment]
Potentially we can create constructors when binding types which implement `Default` trait.
But that does not implemented yet.

**Comment by ryangjchandler** [comment]
Yeah, that's what I had in mind. Deriving `Default` on a struct is simple when there's no properties etc. I'm happy to take a look at that.

Is there any schedule on the next release too? I'm currently using `git` to resolve the package but that's preventing me from releasing anything via Cargo.

**Comment by katyo** [comment]
Not currently I haven't such plans. But I can review and integrate any reasonable changes as soon as possible. PRs are welcome.

**Comment by ryangjchandler** [comment]
@katyo It's mainly the aarch64 support that I PR'd the other day, need it to release my tool.

**Comment by katyo** [comment]
@ryangjchandler Ok, I just publish new minor release.

**Comment by ryangjchandler** [comment]
Awesome, thanks @katyo. Really appreciate it :)

**Comment by katyo** [comment]
@ryangjchandler Have you any questions yet?
Can I close this issue?
