### ISSUE TITLE
Better documentation on writing native modules

### ISSUE THREAD

**Issue by ryangjchandler** [DelSkayn/rquickjs#39]
The documentation for writing native modules is a bit lacking and I'm not entirely sure how to achieve the following:

```js
import Flag from 'io'
```

I'd like `io` to be a native module that I write using Rust. I've got a definition like this:

```rust
#[bind(module, public)]
#[quickjs(bare)]
mod io {
    pub struct Flags;

    impl Flags {
        pub fn new() -> Self {
            Self
        }

        pub fn example(&self) {
            println!("Testing!")
        }
    }
}
```

How do I then register the `Io` struct that is created from the `#[bind]` macro so that importing anything from `io` uses this module?

**Comment by katyo** [comment]
Only named module members is supported by `QuickJS`.
So you might try import it like following:
```JS
import { Flag } from 'io';
```

Of course, documentation still so far from completeness.

**Comment by ryangjchandler** [comment]
Thanks @katyo. I actually went down the route of using a custom resolver & loader tuple to get this working with named imports.

**Comment by ryangjchandler** [comment]
What is the purpose of the module_init macro too? Does it handle the loading of the module etc for me?

**Comment by katyo** [comment]
@ryangjchandler 
This macro provides C function which QuickJS calls to register native module. 
See definition [here](https://docs.rs/rquickjs-core/0.1.2/src/rquickjs_core/value/module.rs.html#158-172).

Usually you don't need it until you implement loadable native module.

**Comment by ryangjchandler** [comment]
Right, I see. I'll probably just stick with my `ModuleLoader` logic for now then since it's a bit more explicit. Thanks!
