### ISSUE TITLE
SIGABRT error when using `Context::Base`

### ISSUE THREAD

**Issue by meskill** [DelSkayn/rquickjs#392]
When I'm trying to run this code:

```rust
use rquickjs::{Runtime, Context};

pub fn main() {
    let runtime = Runtime::new().unwrap();
    let context = Context::base(&runtime).unwrap();
}
```

(please, see the https://github.com/DelSkayn/rquickjs/pull/391 for replication.)

I'm getting the error `terminated by SIGABRT (6)` locally. It also replicates in the github CI with the error `exit code: 0xc0000409`, see [here](https://github.com/tailcallhq/tailcall/actions/runs/11891713729/job/33133055371). 

There is no additional info above the error even with additional debug features.

It worked fine on version `0.5.1`, but starting with `0.6.0` up to `0.7.0` the error is there. 

Also, if I replace `Context::base` with `Context::full` it ends successfully.

**Comment by DelSkayn** [comment]
Thanks for raising the issue!

I fixed it in a commit just now. The fix will be in the next version.

**Comment by DelSkayn** [comment]
Closing issue as it is now fixed.
