### ISSUE TITLE
How to define a function or method that uses variable-length parameters?

### ISSUE THREAD

**Issue by SkadiRust** [DelSkayn/rquickjs#394]

**Comment by DelSkayn** [comment]
You can use the [`Rest`](https://docs.rs/rquickjs/latest/rquickjs/function/struct.Rest.html) type as the argument to the rust callback to take any number of arguments. Or [`Opt`](https://docs.rs/rquickjs/latest/rquickjs/function/struct.Opt.html) to introduce optional arguments.
