### ISSUE TITLE
Best practices to call method of an instance?

### ISSUE THREAD

**Issue by faldez** [DelSkayn/rquickjs#40]
Hi, thank you for the great library. I'm looking to incorporate js for my app.

is there a better way to call method of an instance? currently I'm doing it by defining functions that call the methods and save them into  a persistent.

```rs
ctx.with(|ctx| {

let module = ctx.compile("foo", r#"
import Foo from 'foo';

export const foo = new Foo();

export const doSomething= () => {
    return foo.doSomethin();
}
"#)
.unwrap();

let do_something = Persistent::save(ctx, module.get::<_, Function>("doSomething").unwrap());
})
```

I wonder if there's a better way

**Comment by katyo** [comment]
@faldez You could simply call the method directly. All you need is pass instance via `This` wrapper like the following:
```rust
foo.get::<_, Function>("doSomething").call((This(foo), ...other args));
```

See examples here [function.rs#L339-L367](/DelSkayn/rquickjs/blob/master/core/src/value/function.rs#L339-L367)

**Comment by faldez** [comment]
thank you for your help. I forget to look into tests for examples, will look into it.
