### ISSUE TITLE
Example for Async/issues with Async

### ISSUE THREAD

**Issue by Attacler** [DelSkayn/rquickjs#401]
Hi there,

Im currently trying to get RQuickjs working with Async JS.
For this i want to use a method that runs the provided code.
However if i do try to run it, i currently get the error "WouldBlock" back.
I have searched the internet and this Github in order to get a good idea about how it works but i cannot figure it out...
Can you please give me some pointers into the right direction?
A good example would also be nice :)

The code i currently have:
```rs
use rquickjs::{
    async_with,
    prelude::{Async, Func},
    AsyncContext, AsyncRuntime, Error, Exception, FromJs, Function, Promise, Result, Value,
};

async fn sleep<'js>(msec: u64) {
    let dur = std::time::Duration::from_millis(msec as _);
    tokio::time::sleep(dur).await;
}

fn print(text: String) {
    println!("Script logs: {}", text)
}

pub async fn run_script(code: String) -> Result<String> {
    let rt = AsyncRuntime::new().unwrap();

    let ctx = AsyncContext::full(&rt).await.unwrap();

    let result = async_with!(ctx => |ctx|{
        ctx.globals().set("print", Func::from(print)).unwrap();
        ctx.globals().set("delay", Func::from(Async(sleep))).unwrap();
        let promise = ctx.eval::<Function,_>("async () => { ".to_string() + &code + " }")
        .unwrap();

        let x = promise.call::<(),Promise>(()).unwrap();

        let res: Result<Value> = x.finish();

        if res.is_err() {
            if let Err(Error::Exception) = res {
                let exception = Exception::from_js(&ctx, ctx.catch()).unwrap();

                return Err(format!(
                    "{:?}\n{:?}",
                    exception.message().unwrap(),
                    exception.stack().unwrap()
                ));
            }

            if let Err(Error::WouldBlock) = res {
                // let exception = Exception::from_object(res.unwrap_err()).unwrap();

                return Err(format!(
                    "No more work: WouldBlock"
                ));
            }
            println!("{:?}", res);
            return Err("Unknown error!".to_string());
        }
        println!("{:?}", res);
        let value = res.unwrap();
        let type_of = value.type_of();

        return match type_of {
            rquickjs::Type::String => Ok(value.as_string().unwrap().to_string().unwrap()),
            _ => Ok("".to_string()),
        };
    })
    .await;
    println!("{:?}", result);
    return Ok("".to_string());
}
```

When i try to execute this code it works when using:
```rs
let result = run_script(
        "
        try{
            print(new Date().getTime() + '');
            //await delay(1000);
            let end = new Date();
            return [end.getTime()]
        }catch(e){
            return e.message
        }
    "
        .to_string(),
    )
    .await
```
    but if i try to remove the comments/enable the delay, it will result in:
```
[Running 'cargo run']
Compiling rustQuickJS v0.1.0 (D:\rumcs)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 13.35s
Running `target\debug\rustQuickJS.exe`
Script logs: 1733424426364
Err("No more work: WouldBlock")
result: Ok("")
```
I understand that this error only occurs when the job queue is empty but im not sure how i can make sure that it will have a pending job.
Any pointers into the right direction are welcome :)

**Comment by DelSkayn** [comment]
Calling finish on a promise causes the `WouldBlock` error when no more work can be done except for rust futures. 

Rquickjs has essentially two different job queues one for QuickJS jobs and one for rust futures. QuickJS jobs can be run at any time but rust futures need access to a context. `Promise::finish` doesn't have access to the context needed for running rust futures so it can only run QuickJS jobs. So if a promise is waiting on a rust future to return `finish` returns an error because it cannot make progress.

If a promise might need to wait an on rust future you should turn that promise into a rust future with [`Promise::into_future`](https://docs.rs/rquickjs/latest/rquickjs/promise/struct.Promise.html#method.into_future) and then poll/await that future. This will allow running both rust futures as well as QuickJS jobs until the promise finishes.
