### ISSUE TITLE
Execute compiled script

### ISSUE THREAD

**Issue by d00z3l** [DelSkayn/rquickjs#46]
Is there a way to executed a compiled script? I want to pre-compile a script with `ctx.compile(...)` then evaluate it multiple times without the overhead of the compile step.

**Comment by katyo** [comment]
The new way to work with modules provides functions like [`Module::new`](https://docs.rs/rquickjs/0.1.4/rquickjs/struct.Module.html#method.new) and [`Module::eval`](https://docs.rs/rquickjs/0.1.4/rquickjs/struct.Module.html#method.eval).
See my answer to similar question: https://github.com/DelSkayn/rquickjs/issues/26#issuecomment-825149020

When you want only evaluate module multiple times you can simply clone loaded module before running `eval`.

When you would like to cache bytecode you can use [`Module::<Loaded<Script>>::write_object`](https://docs.rs/rquickjs/0.1.4/rquickjs/struct.Module.html#method.write_object) to get compiled bytecode, and [`Module::<Loaded<Script>>::read_object`](https://docs.rs/rquickjs/0.1.4/rquickjs/struct.Module.html#method.read_object) to load it back.

**Comment by d00z3l** [comment]
Thanks, I gave that a try but I receive None from the return value. I am doing a simple if/else in a bench:

```rust
fn scripts_quickjs_bench(c: &mut Criterion) {

    let script = r#"
        if (get(0) > 2000000) {
            get(1)
        } else {
            get(2)
        }
        "#;

    let rt = rquickjs::Runtime::new().unwrap();
    let ctx = rquickjs::Context::full(&rt).unwrap();

    let api = Api::new();
    let mut rng = rand::thread_rng();

    ctx.with(|ctx|{

        let global = ctx.globals();
        let api_copy = api.clone();
        global.set("get", rquickjs::Func::from(move |index: i32| {
            api_copy.get(index)
        })).unwrap();
        let api_copy = api.clone();
        global.set("set", rquickjs::Func::from(move |index: i32, val: f64| {
            api_copy.set(index, val)
        })).unwrap();

        let m = rquickjs::Module::new(ctx, "script", script).unwrap();
        let byte_code = m.write_object(false).unwrap();

        c.bench_function("scripts_quickjs_bench", |b| b.iter(|| {
            
            let fake_id = rng.gen_range(1..u32::MAX);
            api.set_id(0, fake_id);

            let m = rquickjs::Module::read_object(ctx, &byte_code).unwrap();
            let id : u32 = m.eval().unwrap().as_number().unwrap() as u32;
            if fake_id > 2000000 {
                assert_eq!(id, criterion::black_box(1));
            } else {
                assert_eq!(id, criterion::black_box(2));
            }

        }));
        
    });

}
```

**Comment by katyo** [comment]
@d00z3l: Please, describe your problem in details.

**Comment by d00z3l** [comment]
I want to be able to compile a script up front and then execute many times in a loop similar to the bench. The script doesn't change just external information that can be accessed by an API. Steps are:
1. Create runtime/context
2. Create the API
3. Compile script
4. Start loop
5. Eval script in loop

**Comment by katyo** [comment]
If I uderstand usage scenario right I suppose that your script haven't looks like ES6 module.
Try the following: wrap your JS code to a function and export it. Next, on a Rust side you might prefer evaluate module once, but you could call exported function multiple times.

**Comment by d00z3l** [comment]
Calling the exported functions still requires parsing though? For example `ctx.eval("myExportedFunc()")`?

**Comment by katyo** [comment]
@d00z3l You could (and should) call exported function directly (i.e. without using eval).

**Comment by d00z3l** [comment]
Hi @katyo,

I have tried a few things but can't return a value from module.eval(). Looking at the code it seems to be returning itself (the module). I have looked at the examples but can't find a way to do it. If you could provide some example code that would be really appreciated.

**Comment by d00z3l** [comment]
I have worked it out, I didn't know what you meant by call it directly. Example code:

```rust
let script = r"
       // get(...) calls a rust closure in globals
	export function main() {
		if (get(0) > 2000000) {
			return get(1);
		} else {
			return get(2);
		}
	}";

let m = ctx.compile("script", script).unwrap();
let func: rquickjs::Function = m.get("main").unwrap();
let id : u32 = func.call(()).unwrap();

```
