### ISSUE TITLE
How to access the buffer of a ArrayBuffer?

### ISSUE THREAD

**Issue by paulrouget** [DelSkayn/rquickjs#48]
A JS function calls a Rust function and that argument is a TypedArrayBuffer. How to access that content of that array?

**Comment by katyo** [comment]
@paulrouget Seems bindings for typed arrays hasn't yet implemented for now.

**Comment by katyo** [comment]
@paulrouget I have added initial support for `TypedArrays` (pr #49). Could you help me to test it? And propose some extra tests.

**Comment by katyo** [comment]
Closed due to inactivity for a while.
Feel free to reopen if this issue still alive.
