### ISSUE TITLE
How to use with async / Tokio runtime?

### ISSUE THREAD

**Issue by brocaar** [DelSkayn/rquickjs#56]
First of all thanks for all your work! I have a script that uses your library, for which I would like to use the Tokio runtime. I have been searching for code examples to use this library with an async runtime / Tokio, but I couldn't fine any. The only mention in the documentation that I could find is (for Tokio):

> The method [Runtime::spawn_executor](https://docs.rs/rquickjs/latest/rquickjs/struct.Runtime.html#method.spawn_executor) can be used with [Tokio](https://docs.rs/rquickjs/latest/rquickjs/struct.Tokio.html) to spawn async executor.

Roughly, my code looks like this:

```rust
async fn code_example() -> Result<SomeStruct> {
    let rt = rquickjs::Runtime::new().unwrap();
    let ctx = rquickjs::Context::full(&rt).unwrap();

    let script = r#"
        export function Function(input) {
            return {...};
        }
    "#;

    ctx.with(|ctx| {
        let m = ctx.compile("script", script).unwrap();
        let func: rquickjs::Function = m.get("Function").unwrap();

        let input = rquickjs::Object::new(ctx).unwrap();
        // set some input variables

        let res: rquickjs::Object = func.call((input,)).unwrap();
        Ok(function_which_converts_the_data(&res))
    })
}
```

I guess I need register the Tokio runtime using `rt.spawn_executor(rquickjs::Tokio)`, but what else is needed?

What I would like to implement in the end is something like:
https://docs.rs/tokio/0.2.18/tokio/macro.select.html#avoid-racy-if-preconditions

```rust
async fn some_async_work() {
    // do work
}

#[tokio::main]
async fn main() {
    let mut delay = time::delay_for(Duration::from_millis(50));

    loop {
        tokio::select! {
            _ = &mut delay => {
                println!("operation timed out");
                break;
            }
            _ = some_async_work() => {
                println!("operation completed");
            }
        }
    }
}
```

In this case `some_async_work` would be the function that is responsible for executing the JS code. This would (hopefully) allow me to set a max. execution time, after which the JS code execution can be cancelled (if it runs longer than allowed).

Any help would be appreciated.

**Comment by katyo** [comment]
The example of using rquickjs with tokio looks like the following:
```rs
async fn delay(msec: u32) {
    let duration = std::time::Duration::from_millis(msec as _);
    tokio::time::sleep(duration).await;
}

#[tokio::main]
async fn main() {
    let rt = rquickjs::Runtime::new().unwrap();
    let ctx = rquickjs::Context::full(&rt).unwrap();

    /* spawn async executor using tokio runtime */
    rt.spawn_executor(rquickjs::Tokio);

    /* register async function */
    ctx.with(|ctx| {
        let global = ctx.globals();
        global.set("delay",
            rquickjs::Func::from(|msec| Promised(delay(msec)))
        ).unwrap();
    });

    /* run our async JS code */
    let res: Promise<()> = ctx.with(|ctx| {
        ctx.eval("delay(50)").unwrap()
    });
    res.await.unwrap();

    /* await while async JS code still executing */
    rt.idle().await;
}
```

**Comment by brocaar** [comment]
@katyo does the async executor only works when calling Rust native functions, like in your example where you call `async fn delay`?

My use-case is that the code executed is potentially unsafe. E.g. if somebody would write a for loop that would never end, I want to cancel the script after x time.  As far as I understood, the execution of an async function can be cancelled by dropping the trait (see code example in my first message). Or maybe there is a better way? Maybe it is better if I implement an interrupt handler for this use-case, which then returns true after the execution must timeout (https://docs.rs/rquickjs/latest/rquickjs/struct.Runtime.html#method.set_interrupt_handler).

**Comment by katyo** [comment]
@brocaar Async executor works when calling JS functions too.
If you call async JS function from Rust you can wrap resulting future with timeout to limit execution time.
Alternatively you can await `Runtime::idle`.
I don't recommend you use `Runtime::set_interrupt_handler` for that purpose.

**Comment by brocaar** [comment]
Thanks again @katyo for your feedback. Do you have any particular reason for not using the `set_interrupt_handler` for this?

I figured this could be as easy as:

```rust
    rt.set_interrupt_handler(Some(Box::new(move || SystemTime::now() > max_run_ts)));
```

Where `max_run_ts` is the time after which the execution must be terminated.

Would you be interested if I would contribute some usage example to this repository once I've figured out the best practices? When I was initially looking at this repository, I was hoping to find single file "hello world" example with a string defining the JS code + an example how to call this function using this library. I could contribute for example a sync + async example which hopefully helps others to get started.

**Comment by katyo** [comment]
@brocaar
May be such decision is viable when you really want to change behavior globally for all contexts of your runtime.

Currently you can find many usage examples in tests. Of course documentation needs to be much more better. Any help are welcome. I try review and merge any PRs as soon as possible despite my busy.

**Comment by itribs** [comment]
`
ctx.eval(r"
                async function cycles() {
                    while(true) {
                        await delay(1);
                    }
                }
                cycles();
            ")
`
when 'delay' is called in while(true), the closure in 'set_interrupt_handler' will not be called
