### ISSUE TITLE
Opaque pointers

### ISSUE THREAD

**Issue by jeromegn** [DelSkayn/rquickjs#57]
There's the concept of setting an opaque pointer on a `JS_Value` via `JS_SetOpaque`. I see it's being used for class definitions as well as functions in this crate.

Could there be a way to make a generic type that can store any pointer? Possibly by generating a ClassID for every value of T, lazily.

If not, can I get an example on how to use `JS_SetOpaque` and `JS_GetOpaque` safely? I'm assuming it involves `Box`ing and making sure my opaque pointer is not dropped before the opaque itself.

I'd like to be able to pass an object containing an opaque pointer and converting it back and forth into a `Value` via `IntoJs` and `FromJs`.

**Comment by katyo** [comment]
@jeromegn You can create and export your own class which holds any kind of userdata. This class can be easily transferred between JS and Rust.

**Comment by jeromegn** [comment]
Thank you! I ended up figuring that out this morning 😄
