### ISSUE TITLE
Registering values might cause failed assertions when dropping the runtime

### ISSUE THREAD

**Issue by jeromegn** [DelSkayn/rquickjs#62]
I'm registering some values via the `Ctx::register` function.

I noticed this will cause failed assertions in quickjs if values are not deregistered before dropping the runtime.

```
Assertion failed: (list_empty(&rt->gc_obj_list)), function JS_FreeRuntime, file quickjs.c, line 1981.
```

This makes some sense to me, but you probably have a better idea how to fix it. For now I'm going to deregister them before dropping the runtime.

**Comment by katyo** [comment]
I planned to remove this deprecated API.

**Comment by jeromegn** [comment]
Oh I see. What can I use instead? That functionality is useful :)

**Comment by jeromegn** [comment]
Ok, I should use `Persistent`. That seems to work better!
