### ISSUE TITLE
How to "throw" exceptions from native code?

### ISSUE THREAD

**Issue by jeromegn** [DelSkayn/rquickjs#63]
I've been looking at the docs / tests and I can't seem to find a way to manually throw an exception for native code.

Most useful functions for this are non-public (from outside the crate).

If I panic in a native function, then I will crash my thread. Shouldn't a panic there be caught and thrown in the JS context?

I attempted to create my own `Error` enum that implements `IntoJs` but I couldn't create a new quickjs JS Exception and convert it to a `rquickjs::Value` without using private functions.

Any help would be appreciated. For now I'm going to try and fork the crate to add some functionality...

**Comment by katyo** [comment]
You can just return a Result::Error with corresponding js error to throw exception.

**Comment by jeromegn** [comment]
Do you mean returning a `rquickjs::Error::Exception`?

Maybe a blanket `IntoJs` implementation for `T: std::error::Error` would work well here. It would end up being and exception and show the filename, the stack would have both JS frames and native frames, etc. Of course the message would be `error.to_string()`.

**Comment by katyo** [comment]
Yes.
As you can see when error result returned from function it throws JS exception: https://github.com/DelSkayn/rquickjs/blob/b912787591377f2c1fece1eace454d78bab33bad/core/src/value/function/ffi.rs#L83

**Comment by DelSkayn** [comment]
Closing this issue as the problem seems to be solved.
