### ISSUE TITLE
Support for Date type value conversion?

### ISSUE THREAD

**Issue by brocaar** [DelSkayn/rquickjs#66]
Has the rquickjs library support for converting a Rust timestamp (e.g. `chrono` `DateTime<Utc>` to / from JS `Date` type? Use-cases are calling a JS function with a `Date` type parameter in its signature, or a JS function returning a `Date` type.

I could not find any reference to this in the code to this.

**Comment by katyo** [comment]
@brocaar 
Seems currently it lack support for date/time types conversion.
But I think it quite easy to implement. Could you try to do it?
PRs are welcome. I can review and merge it soon.

**Comment by brocaar** [comment]
I'll give it a try :)
