### ISSUE TITLE
Accessing variable from within a module

### ISSUE THREAD

**Issue by tobiemh** [DelSkayn/rquickjs#73]
Hi,

I am trying to create a module which operates on a database connection.

The database connection is created in Rust, before the rquickjs runtime is created and executed.

At the moment I can't figure out how to pass the transaction into the module, so that the methods on the module are able to access and call methods on the database transaction.

I thought I might be able to use [`Ctx.register`](https://docs.rs/rquickjs/latest/rquickjs/struct.Ctx.html#method.register) to set a non-accessible variable, which I could then access using the `Ctx` when defining the Module manually, but I don't see anyway of knowing what [`RegisteryKey`](https://docs.rs/rquickjs/latest/rquickjs/struct.RegisteryKey.html) is returned.

I guess what I'm looking for is some way to pass a variable (possibly even without converting it to a rquickjs::Value), which can then be accessed on the Ctx wherever I need. Not sure if this is possible...?

```rust
let txn = DATABASE.new_transaction(); // Example only!
let run = Runtime::new().unwrap();
let ctx = Context::full(&run).unwrap();
ctx.with(|ctx| {
    // Here I want to make the database transaction variable available to the Ctx
    // The following line of code is an idea, but I don't see how to pass the key to the Module
    let key = ctx.register(txn);
    // Execute the code
    ctx.eval(src)
})
```

```rust
impl ModuleDef for Package {
    fn load<'js>(_ctx: Ctx<'js>, module: &Module<'js, Created>) -> Result<()> {
        module.add("test")?;
        Ok(())
    }
    fn eval<'js>(ctx: Ctx<'js>, module: &Module<'js, Loaded<Native>>) -> Result<()> {
        module.set("test", Function::new(ctx, Async(|| async {
            // Here I want to retrieve the database transaction here and use it to query the database
        })))?;
        Ok(())
    }
}
```

Thanks in advance!

**Comment by DelSkayn** [comment]
Hi!

The registry functionality was not really intended for your use case. It is a semi-deprecated method of being able to handle javascript objects outside of `ctx.with()` closure, to be replaced by [`Presistent`](https://docs.rs/rquickjs/latest/rquickjs/struct.Persistent.html). 

There is currently no real support in the library for what you are trying to do. I think the best way to, right now, do what you are trying to accomplish is to store the transaction somewhere in the contexts global object.

**Comment by katyo** [comment]
Looks like resolved.
