### ISSUE TITLE
Unable to load a JavaScript module in Rust

### ISSUE THREAD

**Issue by tobiemh** [DelSkayn/rquickjs#78]
Hi!

I'm trying to load a module in Rust, and I'm not sure whether I'm doing something wrong, or if there is an error.

I am defining a module like this (and this works fine and is able to be imported fine from the JavaScript code)...

```rs
#[js::bind(module, public)]
#[quickjs(bare)]
#[allow(non_upper_case_globals)]
pub mod package {
    pub const version: &str = env!("CARGO_PKG_VERSION");
}
```
or
```rs
pub struct Package;

impl ModuleDef for Package {
    fn load<'js>(_ctx: Ctx<'js>, module: &Module<'js, Created>) -> Result<()> {
        module.add("version")?;
    }
    fn eval<'js>(ctx: Ctx<'js>, module: &Module<'js, Loaded<Native>>) -> Result<()> {
        module.set("version", env!("CARGO_PKG_VERSION"))?;
    }
}
```

However I am then trying to load the module, and assign it to a global variable. But loading the module in any way, causes the application to exit with just `Abort trap: 6`. I'm not sure if it is something that I'm doing wrong, or if there is an issue in the code?
```rs
let run = Runtime::new().unwrap();
let ctx = Context::full(&run).unwrap();
ctx.with(|ctx| {
    let global = ctx.globals();
    let pkg = Module::new_def::<mypackage::Package, _>(ctx, "mypackage")?.eval()?.into_value();
    global.set("pkg", pkg)?;
    ctx.eval(src)
})
```

This method however works perfectly, but I'd prefer to load the module without having to compile and execute the javascript `import` statement.
```rs
let run = Runtime::new().unwrap();
let ctx = Context::full(&run).unwrap();
ctx.with(|ctx| {
    let global = ctx.globals();
    let pkg = ctx.compile("temp", "import * as all from 'mypackage'; export default all")?.get::<_, Value>("default")?;
    global.set("pkg", pkg)?;
    ctx.eval(src)
})
```

**Comment by DelSkayn** [comment]
The `Value` returned from `Module::into_value` in the line:
```rust
let pkg = Module::new_def::<mypackage::Package, _>(ctx, "mypackage")?.eval()?.into_value();
```
does not contain the values exported by the module but the module object itself.
Modules are not valid javascript objects and can't be the value of a object property; this is probably why quickjs aborts.
Modules can be turned into a `Value` because quickjs internally handles them as generic javascript values.

I see this might be somewhat confusing, I should probably remove `into_value` for `Module`.

The only way to access module exports is to use `Module::get`, `Module::names`, or `Module::entries`.

**Comment by tobiemh** [comment]
Ah ok, that makes sense. However the `Abort trap: 6` happens even if I just try to load the module, without even trying to access any of the module contents, or entries...

```rs
Module::new_def::<mypackage::Package, _>(ctx, "mypackage")?;
```

**Comment by DelSkayn** [comment]
You're right! The module was freed to early. Fixed in #79. That should fix the abort.

**Comment by tobiemh** [comment]
Perfect @DelSkayn ! That definitely fixes the issue 😀. Do you have any idea/plans when a new release version might be done?

**Comment by DelSkayn** [comment]
I have released a new version. Closing this issue as it is resolved.
