### ISSUE TITLE
Idea: Storing current ctx in thread-local storage

### ISSUE THREAD

**Issue by katyo** [DelSkayn/rquickjs#8]
To get things much easier we can store current ctx in thread-local storage.

So we can avoid storing it in `ObjectRef`.
Also we can add `FromIterator` trait implementations for an `Array` and an `Object`.
And etc.

**Comment by DelSkayn** [comment]
`Ctx` is used for a lot of safety guarantees in the library.
The lifetime on `Ctx` locks objects such that they can only be used with that context.
Take for instance the following code:
```rust
context_1.with(|ctx_1|{
   let obj = Object::new(ctx_1)?;
   let runtime = Runtime::new();
   let context_2 = Context::full(&runtime);
   context_2.with(|ctx_2|{
      // This results in undefined behaviour
      ctx_2.globals().set("foo",obj)
   })
})
```
The lifetime on `Ctx` is defined in such a way that the above code will result in an compile error.

I am not entirely sure since it has been a while since I worked with this code base but storing `Ctx` in thread-local storage will require one to change its lifetime as thread-local requires `'static`.
If you then create objects with that context they are no longer protected by the lifetime guarantee and can thus trigger the undefined behavior above.

**Comment by DelSkayn** [comment]
This also does not work well with the `MultiWith` trait, which allows one to use multiple contexts of the same runtime together.

**Comment by katyo** [comment]
Sounds reasonable. Safety warranties should not be compromised in any case.

**Comment by DelSkayn** [comment]
JsRef (and all the typedefs deriving from it) need a pointer to a Context in order to be able to free the underlying quickjs object in its drop method. So we are kinda stuck with storing pointers with every object.

**Comment by katyo** [comment]
As I understand correctly this objects cannot outlive ctx.
So we may just store pointer to ctx in some known location (for ex. in TLS) to avoid duplicating refs in each one.
This is semantically correct and safety warranties does not compromised.

**Comment by DelSkayn** [comment]
I did a quick test with how different `Ctx`'s impact the semantics of code.
Using a certain `Ctx` with a certain object changes which global the object references.

example:
```rust
use rquickjs::{Context, MultiWith, Object, Runtime, Value};

fn main() {
    let rt = Runtime::new().unwrap();
    let ctx_1 = Context::full(&rt).unwrap();
    let ctx_2 = Context::full(&rt).unwrap();
    MultiWith::with((&ctx_1, &ctx_2), |(ctx_1, ctx_2)| {
        ctx_1.globals().set("foo", 1).unwrap();
        ctx_2.globals().set("foo", 2).unwrap();
        let mut obj: Object = ctx_1
            .eval("({ get test() { return globalThis.foo } })")
            .unwrap();
        println!("{:?}", obj.get::<_, Value>("test")); // prints 1

        // Quick hack to be able to change ctx object stored with the object
        rquickjs::js_ref_swap_ctx(&mut obj.0, ctx_2);

        println!("{:?}", obj.get::<_, Value>("test")); // prints 2
    })
}
```
Using a single `Ctx` stored somewhere can result in somewhat unpredictable behavior as user might not know which `Ctx` is the globally stored one.

But this also shows a larger problem when dealing with multiple contexts:
It is currently somewhat difficult to track which context an object belongs to.
By default an object belongs to the context it was created in, but the moment it is passed to an object of another context it's context will change to.
Furthermore there is currently no method the change the context of an object directly from rust.

So I see two solutions:
- Have all methods which require a context take `Ctx` as an argument; store the runtime in TLS for freeing objects. OR:
- Add a method to objects to allow changing it's stored `Ctx`

The first one will make a lot of methods more verbose but does make it more clear which context an object belongs to and prevents duplication as it no longer needs to store Ctx in each object.
The second makes using methods on objects less verbose at the cost of slightly more confusion when dealing with multiple objects and an additional 8 bytes added to each object.

Thoughts?

**Comment by katyo** [comment]
I proceeded from that we can use only one context at a time.
So previously offered solution does not works in case of using more than single context simultaneously.

Originally it is used by hardware device support crates which provides access to peripheral registers.
This works fine because each peripheral unit is an unique entity.

**Comment by DelSkayn** [comment]
Closing this for now
