### ISSUE TITLE
Keeping a callback on the Rust side

### ISSUE THREAD

**Issue by bspot** [DelSkayn/rquickjs#86]
Let me apologize in case I'm missing the obvious, but I don't know how to approach this:

I want to define a struct on the Rust side that keeps hold of a JS function and exposes a function to the JS side that in turn will call the callback.

```
// Does not compile

#[bind(object)]
#[quickjs(bare)]
mod storage {
    pub struct Holder {
        pub callback: rquickjs::Function // ????
    }

    impl Holder {
        // constructor
        pub fn new(callback: rquickjs::Function) -> Self {
            Self { callback }
        }

        // instance method
        pub fn run(&self) -> () {
            self.callback.call::<(), ()>(());
        }
    }
}
```

Of course, this doesn't work because to use `rquickjs::Function`, I have to specify a lifetime on my `Holder` struct, which the `bind` macro does not support.
But even if I implement the binding manually, it doesn't work:

1. If I use `Function` as the type of the callback, the program crashes with `quickjs.c:1981: JS_FreeRuntime: Assertion 'list_empty(&rt->gc_obj_list)' failed.`; probably because the `Function` survives the `ctx.bind`. 

2. I can't use a `Persistent<Function>`, because I don't have access to the `Ctx` in my `new` and `run` functions.

In addition, the same issue arises if I want to store a value I can't convert to a Rust type, e.g. `Object` or a generic `Value`.

**Comment by katyo** [comment]
@bspot 
You can get access to the context by adding it as an argument to a function.
