### ISSUE TITLE
Unable to build on windows

### ISSUE THREAD

**Issue by zacreid** [DelSkayn/rquickjs#88]
Hi all,
  Keep getting this error when trying to build for windows, I've been unable to figure out what files I'm missing. Any help is appreciated.

```
Compiling rquickjs-sys v0.1.7
error: failed to run custom build command for `rquickjs-sys v0.1.7`

Caused by:
  process didn't exit successfully: `C:\Users\Zac Reid\Documents\GitHub\surrealdb-test\target\debug\build\rquickjs-sys-136287e45d48a699\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=CARGO_FEATURE_EXPORTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_BINDGEN
  cargo:rerun-if-env-changed=CARGO_FEATURE_UPDATE_BINDINGS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_BYTECODE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_GC_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_FREE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_LEAKS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MEM
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_OBJECTS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_ATOMS
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_SHAPES
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_MODULE_RESOLVE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_PROMISE
  cargo:rerun-if-env-changed=CARGO_FEATURE_DUMP_READ_OBJECT

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', C:\Users\Zac Reid\.cargo\registry\src\github.com-1ecc6299db9ec823\rquickjs-sys-0.1.7\build.rs:136:10
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\std\src\panicking.rs:584
     1: core::panicking::panic_fmt
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\panicking.rs:142
     2: core::result::unwrap_failed
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library\core\src\result.rs:1805
     3: enum$<core::result::Result<std::process::Child,std::io::error::Error> >::unwrap<std::process::Child,std::io::error::Error>
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\result.rs:1098
     4: build_script_build::patch<ref$<std::path::Path>,std::path::PathBuf>
               at .\build.rs:131
     5: build_script_build::main
               at .\build.rs:98
     6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\core\src\ops\function.rs:248
```

**Comment by powpingdone** [comment]
You need to install `patch`. #87 clarifies this.

**Comment by Cody-Duncan** [comment]
I'd like to request that this dependency be called out in the README.md, along with a recommended source for installing `patch`. 

*Rationale*: As a windows user this is an unfamiliar cli tool, so it took me some digging just to understand that `patch` was an executable.

If you want to be more cavalier, it should be possible to remove the dependency on patch by patching in the build script.
It looks like [`cargo patch`](https://crates.io/crates/cargo-patch) command uses the [`patch`](https://crates.io/crates/patch) crate to read and then applies the patch manually.
https://github.com/itmettkeDE/cargo-patch/blob/master/src/main.rs

**Comment by Cody-Duncan** [comment]
P.S. If `patch` fails execution, the build script doesn't catch it
```
  Appliyng patch patches\check_stack_overflow.patch
  Appliyng patch patches\infinity_handling.patch
  Appliyng patch patches\atomic_new_class_id.patch
  Appliyng patch patches\basic_msvc_compat.patch
  ```

In my case, I forgot to move a dependent dll into the directory with patch.exe, and running `path --help` emitted an error.
```
patch.exe - System error:
The program can't start because msys-2.0.dll is missing from your computer.
Try reinstalling the program to fix this problem.
```

The build script went on to build the c files un-patched.

**Comment by GalaxyS7** [comment]
Don't forget for Rust to be able to execute patch.exe from anywhere you have to add the path to your "path" environment variable.

Btw: Git comes with a patch.exe in C:\Program Files\Git\usr\bin. I simply added this path to my "path" variable and it worked.

**Comment by joeyame** [comment]
This is an issue on Manjaro Linux too. Can cargo not search for and install this dependency? I've never had issues using any libraries until I decided to utilize a project that depends on this one.

**Comment by danielSanchezQ** [comment]
I am having troubles as well. With mingw. Missing a reference:

```
rquickjs-sys-e831da8d902e6506/out/quickjs.c:53894: undefined reference to `clock_gettime'
```

Tried adding the `-lrt` flag, but didn't worked:
```
[build]
rustflags = ["-C", "link-args=-lrt"]
```

**Comment by ehsanonline** [comment]
you can download patch from here http://gnuwin32.sourceforge.net/downlinks/patch-bin-zip.php

**Comment by SUPERetnad01** [comment]
How do I install this patch on Windows? I tried downloading it and adding it to the environment variables, but it opens a different window when you try the command.

**Comment by DelSkayn** [comment]
With the switch from Quickjs to Quickjs-ng we are no longer applying patches to quickjs, so there is no need for the patch binary being installed which should fix this issue.
