### ISSUE TITLE
Embedded modules loaded multiple times

### ISSUE THREAD

**Issue by bspot** [DelSkayn/rquickjs#89]
When the name of a module in a `Bundle` is not the same as the module's name in the embedded bytecode, the module will be re-loaded every time it is imported.

Reproduction: https://github.com/bspot/repro_bundled_loaded_twice

```
#[embed(path = "./js")]
mod embedded_module {}
```

The name in the `Bundle` is `embedded_module`, but the name in the bytecode is `js/embedded_module.js`. 

Since `Bundle::resolve()` returns the passed in name (`embedded_module`) unchanged, this is the name QuickJS uses to look up the module in the context's loaded modules. The name of the loaded module is `js/embedded_module.js` because comes from the bytecode.

So QuickJS doesn't find the loaded module and loads it again.

**Comment by stevefan1999-personal** [comment]
I noticed this issue as well, when I want to make some internal modules in JS that got compiled to bytecode but it seems like the file resolver had took the precedence

**Comment by DelSkayn** [comment]
Closing this issue as it was fixed in #142. 

In the future I will have another pass at the embed macro as I find that it's current functionality as somewhat unclear and the implementation is a bit of a hack.
