### ISSUE TITLE
Fix race condition when using runtimes in parallel

### ISSUE THREAD

**Issue by DelSkayn** [DelSkayn/rquickjs#9]
Quickjs uses a global variable to create unique identifiers for class id's.
The parallel feature assumes that just mutexing runtime is enough to make quickjs save for parallel use.
Unfortunately, this global variable breaks this assumption.

TODO|:
- [ ] Create a patch for quickjs to fix this issue.

**Comment by katyo** [comment]
If you mean usage of Opaque associated with Runtime, I think runtime locking already guards it.
Can you take an example of race condition?

**Comment by DelSkayn** [comment]
In quickjs itself there is a variable `js_class_id_alloc` (quickjs.c line 1192), this variable is used to give classes there own unique ID. 
This variable is a true global, i.e. used by every runtime you can create and not contained in an object.
So the race condition can happen when two runtimes simultaneously try to create a unique class ID, by incrementing the variable.

Now that I think about it this might not cause error, since runtimes are isolated of each other so a runtime can never interact with a class which does not have a unique ID in its own runtime. But it is still undefined behavior so it might cause errors due to optimizations with invalid assumptions.

**Comment by katyo** [comment]
I think we can simply do not allocate class ids via calling `JS_NewClassID`. Because ids is simple u32 values which generates via incrementing by one, we may simply use Rust's atomic u32 with reasonably big initial value (say 10_000) to avoid overlapping with ids which was generated by QuickJS.

**Comment by katyo** [comment]
In #18 I moved call of `JS_NewClassID` to runtime init.

**Comment by katyo** [comment]
Sometimes classes-related tests fails (like a [here](/DelSkayn/rquickjs/runs/1629550567?check_suite_focus=true#step:12:161)).
I assume taht such behavior related to concurrent running of tests which calls `JS_NewClassID`.
I already patched this function using atomic allocation of class ids but seems it does not solves the problem finally.
Looks like we must also turn static ids of our classes to be atomic. Hope it help.
@DelSkayn What are you think?

**Comment by katyo** [comment]
Can we close this issue too?
